package vault

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	section1Re = regexp.MustCompile(`(?i)^#+\s*(?:1\.\s*)?Architectural.*$`)
	section2Re = regexp.MustCompile(`(?i)^#+\s*(?:2\.\s*)?Schema.*$`)
	section3Re = regexp.MustCompile(`(?i)^#+\s*(?:3\.\s*)?Technical Trade-[Oo]ffs.*$`)

	// subHeadingRe matches headings inside callout bodies (e.g. #### Title)
	subHeadingRe = regexp.MustCompile(`^#+\s+(.*)$`)

	// footerRe matches legacy and current auto-generated footers
	footerRe = regexp.MustCompile(`(?i)^\*Auto-generated by .*?\*$`)
)

const (
	MigratedFooter = "*Auto-generated by VaultChron (migrated to v3 callouts)*"
)

// Slugify converts a project name to a URL-safe slug by lowercasing,
// replacing sequences of non-alphanumeric characters with a single hyphen,
// and trimming leading/trailing hyphens.
func Slugify(name string) string {
	lower := strings.ToLower(name)
	var b strings.Builder
	inDash := false
	for _, r := range lower {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			inDash = false
		} else if !inDash {
			b.WriteRune('-')
			inDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// GetSlug returns the project slug for a given project name.
// Deprecated: Use Slugify directly.
func GetSlug(projectName string) string {
	return Slugify(projectName)
}

// Frontmatter holds parsed YAML frontmatter fields.
type Frontmatter struct {
	Date         string
	Project      string
	TotalCommits string
	Model        string
	Generated    string
	Extra        []string
}

// ParseFrontmatter extracts YAML frontmatter lines from markdown content.
func ParseFrontmatter(content string) (fm Frontmatter, body string, hasFM bool) {
	if !strings.HasPrefix(strings.TrimSpace(content), "---") {
		return fm, content, false
	}

	lines := strings.Split(content, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return fm, content, false
	}

	endIdx := -1
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "---" {
			endIdx = i
			break
		}
	}

	if endIdx == -1 {
		return fm, content, false
	}

	for i := 1; i < endIdx; i++ {
		line := lines[i]
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		parts := strings.SplitN(trimmed, ":", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])

		switch key {
		case "date":
			fm.Date = val
		case "project":
			fm.Project = val
		case "total_commits":
			fm.TotalCommits = val
		case "model":
			fm.Model = val
		case "generated":
			fm.Generated = val
		case "tags":
			// skip legacy tags, will be normalized
		default:
			if !strings.HasPrefix(line, "  - ") && !strings.HasPrefix(line, "    - ") {
				fm.Extra = append(fm.Extra, line)
			}
		}
	}

	body = strings.Join(lines[endIdx+1:], "\n")
	return fm, body, true
}

// RenderFrontmatter returns the normalized YAML frontmatter.
func RenderFrontmatter(fm Frontmatter, projectName string) string {
	var buf strings.Builder
	buf.WriteString("---\n")
	if fm.Date != "" {
		buf.WriteString(fmt.Sprintf("date: %s\n", fm.Date))
	}
	proj := fm.Project
	if proj == "" {
		proj = projectName
	}
	buf.WriteString(fmt.Sprintf("project: %s\n", proj))

	slug := Slugify(proj)
	buf.WriteString("tags:\n")
	buf.WriteString("  - type/devlog\n")
	buf.WriteString(fmt.Sprintf("  - project/%s\n", slug))
	buf.WriteString("  - lang/go\n")

	if fm.TotalCommits != "" {
		buf.WriteString(fmt.Sprintf("total_commits: %s\n", fm.TotalCommits))
	}
	if fm.Model != "" {
		buf.WriteString(fmt.Sprintf("model: %s\n", fm.Model))
	}
	if fm.Generated != "" {
		buf.WriteString(fmt.Sprintf("generated: %s\n", fm.Generated))
	}
	for _, extra := range fm.Extra {
		buf.WriteString(extra + "\n")
	}
	buf.WriteString("---\n")
	return buf.String()
}

// cleanSectionTitle strips markdown header symbols and numbering like "1. " from a header line.
func cleanSectionTitle(headerLine string) string {
	line := strings.TrimSpace(headerLine)
	line = strings.TrimLeft(line, "#")
	line = strings.TrimSpace(line)
	// Strip leading "1. ", "2. ", "3. "
	if len(line) >= 3 && line[0] >= '0' && line[0] <= '9' && line[1] == '.' && line[2] == ' ' {
		line = strings.TrimSpace(line[3:])
	}
	return line
}

// formatCallout converts a section's title and body into an Obsidian callout.
func formatCallout(calloutType, title string, bodyLines []string) string {
	var buf strings.Builder
	if title != "" {
		buf.WriteString(fmt.Sprintf("> [!%s] %s\n", calloutType, title))
	} else {
		buf.WriteString(fmt.Sprintf("> [!%s]\n", calloutType))
	}

	// Clean body lines (remove trailing empty lines and trailing ---)
	lastNonEmpty := -1
	for i := len(bodyLines) - 1; i >= 0; i-- {
		t := strings.TrimSpace(bodyLines[i])
		if t != "" && t != "---" {
			lastNonEmpty = i
			break
		}
	}
	if lastNonEmpty >= 0 {
		bodyLines = bodyLines[:lastNonEmpty+1]
	} else {
		bodyLines = nil
	}

	// Skip leading empty lines
	startIdx := 0
	for startIdx < len(bodyLines) && strings.TrimSpace(bodyLines[startIdx]) == "" {
		startIdx++
	}
	bodyLines = bodyLines[startIdx:]

	if len(bodyLines) > 0 {
		buf.WriteString(">\n")
	}

	for _, line := range bodyLines {
		t := strings.TrimSpace(line)
		if t == "---" {
			continue
		}
		if t == "" {
			buf.WriteString(">\n")
			continue
		}

		// Convert internal markdown headers (e.g. #### Title) into bold text to prevent broken callouts
		if subHeadingRe.MatchString(line) {
			m := subHeadingRe.FindStringSubmatch(line)
			headerText := strings.TrimSpace(m[1])
			buf.WriteString(fmt.Sprintf("> **%s**\n", headerText))
			continue
		}

		buf.WriteString(fmt.Sprintf("> %s\n", line))
	}

	return buf.String()
}

// MigrateContent transforms legacy note content into the v3 callout taxonomy.
func MigrateContent(content string, projectName, date string) (string, error) {
	fm, body, _ := ParseFrontmatter(content)
	if fm.Project != "" {
		projectName = fm.Project
	}
	if fm.Date != "" {
		date = fm.Date
	}

	// Check if already migrated to v3 callouts
	alreadyHasAbstract := strings.Contains(body, "> [!abstract]")
	alreadyHasTelemetry := strings.Contains(body, "> [!note]- 📊 Session Telemetry")

	if alreadyHasAbstract && alreadyHasTelemetry {
		// Just ensure frontmatter tags and footer are up to date
		newFM := RenderFrontmatter(fm, projectName)

		// Update footer in body if needed
		bodyLines := strings.Split(body, "\n")
		var newBodyLines []string
		for _, line := range bodyLines {
			if footerRe.MatchString(strings.TrimSpace(line)) {
				newBodyLines = append(newBodyLines, MigratedFooter)
			} else {
				newBodyLines = append(newBodyLines, line)
			}
		}

		cleanBody := strings.TrimSpace(strings.Join(newBodyLines, "\n"))
		return newFM + "\n" + cleanBody + "\n", nil
	}

	// Parse sections from body
	scanner := bufio.NewScanner(strings.NewReader(body))
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}

	var breadcrumbLine string
	var titleLine string
	var introLines []string
	var sec1Title string
	var sec1Lines []string
	var sec2Title string
	var sec2Lines []string
	var sec3Title string
	var sec3Lines []string
	var footerFound bool

	currentSection := 0 // 0: pre-section (intro/telemetry), 1: sec1, 2: sec2, 3: sec3

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Check for footer
		if footerRe.MatchString(trimmed) {
			footerFound = true
			continue
		}

		// Detect breadcrumb bar
		if strings.Contains(line, "[[00-Dev-Index") {
			breadcrumbLine = trimmed
			continue
		}

		// Detect main title
		if (strings.HasPrefix(trimmed, "# ") || (strings.HasPrefix(trimmed, "### ") && strings.Contains(trimmed, "Devlog"))) && titleLine == "" && currentSection == 0 {
			titleText := strings.TrimLeft(trimmed, "#")
			titleLine = "# " + strings.TrimSpace(titleText)
			continue
		}

		// Detect section 1
		if section1Re.MatchString(trimmed) {
			currentSection = 1
			sec1Title = cleanSectionTitle(trimmed)
			continue
		}

		// Detect section 2
		if section2Re.MatchString(trimmed) {
			currentSection = 2
			sec2Title = cleanSectionTitle(trimmed)
			continue
		}

		// Detect section 3
		if section3Re.MatchString(trimmed) {
			currentSection = 3
			sec3Title = cleanSectionTitle(trimmed)
			continue
		}

		switch currentSection {
		case 0:
			// Pre-section lines (intro prose, telemetry, divider)
			if trimmed == "---" {
				continue
			}
			if trimmed == "## Overview" {
				continue
			}
			if trimmed != "" {
				introLines = append(introLines, line)
			}
		case 1:
			sec1Lines = append(sec1Lines, line)
		case 2:
			sec2Lines = append(sec2Lines, line)
		case 3:
			sec3Lines = append(sec3Lines, line)
		}
	}

	var out bytes.Buffer

	// 1 & 2. Frontmatter
	out.WriteString(RenderFrontmatter(fm, projectName))
	out.WriteString("\n")

	// 3. Breadcrumb bar
	if breadcrumbLine != "" {
		out.WriteString(breadcrumbLine + "\n\n---\n\n")
	} else {
		out.WriteString(fmt.Sprintf("[[00-Dev-Index|🏠 Index]] / [[Projects/%s/Overview|%s]]\n\n---\n\n", projectName, projectName))
	}

	// Title
	if titleLine != "" {
		out.WriteString(titleLine + "\n\n")
	} else if date != "" {
		out.WriteString(fmt.Sprintf("# Technical Devlog: %s – %s\n\n", projectName, date))
	}

	// 7. Session Telemetry Callout
	out.WriteString("> [!note]- 📊 Session Telemetry\n")
	hasCommitBullet := false
	for _, l := range introLines {
		if strings.Contains(l, "**Commits:**") {
			hasCommitBullet = true
			break
		}
	}
	if !hasCommitBullet && fm.TotalCommits != "" {
		out.WriteString(fmt.Sprintf("> - **Commits:** %s\n", fm.TotalCommits))
	}
	for _, l := range introLines {
		t := strings.TrimSpace(l)
		if t == "" {
			continue
		}
		if strings.HasPrefix(t, "- ") || strings.HasPrefix(t, "* ") {
			out.WriteString(fmt.Sprintf("> - %s\n", strings.TrimLeft(t, "-* ")))
		} else if strings.HasPrefix(t, "**") {
			out.WriteString(fmt.Sprintf("> - %s\n", t))
		} else {
			out.WriteString(fmt.Sprintf("> - %s\n", t))
		}
	}
	out.WriteString("\n")

	// 4. Section 1 -> > [!abstract]
	if sec1Title == "" {
		sec1Title = "Architectural Features Implemented"
	}
	out.WriteString(formatCallout("abstract", sec1Title, sec1Lines))
	out.WriteString("\n")

	// 5. Section 2 -> > [!info]
	if sec2Title == "" {
		sec2Title = "Schema, Data Contracts, & Routing Logic"
	}
	out.WriteString(formatCallout("info", sec2Title, sec2Lines))
	out.WriteString("\n")

	// 6. Section 3 -> > [!warning]
	if sec3Title == "" {
		sec3Title = "Technical Trade-Offs & Structural Changes"
	}
	out.WriteString(formatCallout("warning", sec3Title, sec3Lines))
	out.WriteString("\n")

	// 8. Footer
	_ = footerFound
	out.WriteString("---\n\n")
	out.WriteString(MigratedFooter + "\n")

	return out.String(), nil
}

// MigrateFile reads, transforms, and safely overwrites a single devlog file
// using an atomic temporary file write. Returns true if file was modified.
func MigrateFile(filePath string) (bool, error) {
	raw, err := os.ReadFile(filePath)
	if err != nil {
		return false, fmt.Errorf("reading file %s: %w", filePath, err)
	}

	content := string(raw)

	// Deduce projectName and date from path: .../Projects/<Project>/Devlog/<Date>.md
	parts := strings.Split(filepath.Clean(filePath), string(filepath.Separator))
	var projectName, date string
	for i := len(parts) - 1; i >= 0; i-- {
		if parts[i] == "Devlog" && i > 0 && i < len(parts)-1 {
			projectName = parts[i-1]
			filename := parts[i+1]
			date = strings.TrimSuffix(filename, ".md")
			break
		}
	}

	migrated, err := MigrateContent(content, projectName, date)
	if err != nil {
		return false, fmt.Errorf("migrating content for %s: %w", filePath, err)
	}

	if migrated == content {
		return false, nil
	}

	// Atomic write: write to temp file first, then rename
	if err := writeFileAtomic(filePath, []byte(migrated), 0o644); err != nil {
		return false, fmt.Errorf("writing migrated file %s: %w", filePath, err)
	}

	return true, nil
}

// MigrateVault finds and migrates all devlog markdown files under <vaultPath>/Projects/*/Devlog/*.md.
// Returns list of modified file paths.
func MigrateVault(vaultPath string) ([]string, error) {
	pattern := filepath.Join(vaultPath, "Projects", "*", "Devlog", "*.md")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return nil, fmt.Errorf("globbing devlog files: %w", err)
	}

	var modified []string
	for _, file := range matches {
		changed, err := MigrateFile(file)
		if err != nil {
			return modified, fmt.Errorf("failed migrating %s: %w", file, err)
		}
		if changed {
			modified = append(modified, file)
		}
	}

	return modified, nil
}
