package vault

import (
	"strings"
	"testing"
)

const sampleLegacyDevlog = `---
date: 2026-08-20
generated: 2026-09-26 03:37:03
project: AcmeWidgets.com
total_commits: 9
model: gemini-3.5-flash-lite
---

# Technical Devlog: AcmeWidgets.com – 2026-08-20

This devlog details architectural updates, schema/routing patterns, and structural refactorings implemented across 9 commits on August 20, 2026.

---

### 1. Architectural Features Implemented

* **Sitemap Discovery & XML Parsing (Slice 2, ADR-0012):**
  * Added capabilities to parse XML sitemaps within the provider discovery pipeline.
* **Atomic Provider Seed Job Enqueuing:**
  * Implemented EnqueueSeedCrawl in SQLite repository.

---

### 2. Schema, Data Contracts, & Routing Logic

#### Database Schema (Test Fixtures & Dependencies)
The underlying database interactions rely on SQLite schema structures:
* Transactional Job Enqueue Contract.

---

### 3. Technical Trade-Offs & Structural Changes

* **Deduplication of Headless Chrome Implementation:**
  * Eliminated duplicated chromeRenderer concrete implementations.

---

*Auto-generated by Hist Devlog Backfiller (gemini-3.5-flash-lite)*
`

func TestMigrateContent(t *testing.T) {
	migrated, err := MigrateContent(sampleLegacyDevlog, "AcmeWidgets.com", "2026-08-20")
	if err != nil {
		t.Fatalf("MigrateContent failed: %v", err)
	}

	// 1. Verify frontmatter
	if !strings.Contains(migrated, "project: AcmeWidgets.com") {
		t.Errorf("missing project in frontmatter")
	}
	if !strings.Contains(migrated, "date: 2026-08-20") {
		t.Errorf("missing date in frontmatter")
	}
	if !strings.Contains(migrated, "total_commits: 9") {
		t.Errorf("missing total_commits in frontmatter")
	}
	if !strings.Contains(migrated, "model: gemini-3.5-flash-lite") {
		t.Errorf("missing model in frontmatter")
	}

	// 2. Verify normalized tags
	expectedTags := "tags:\n  - type/devlog\n  - project/acmewidgets-com\n  - lang/go"
	if !strings.Contains(migrated, expectedTags) {
		t.Errorf("expected tags %q not found in:\n%s", expectedTags, migrated)
	}

	// 3. Verify breadcrumb bar
	expectedBreadcrumb := "[[00-Dev-Index|🏠 Index]] / [[Projects/AcmeWidgets.com/Overview|AcmeWidgets.com]]"
	if !strings.Contains(migrated, expectedBreadcrumb) {
		t.Errorf("expected breadcrumb %q not found", expectedBreadcrumb)
	}

	// 4. Verify callouts
	if !strings.Contains(migrated, "> [!note]- 📊 Session Telemetry") {
		t.Errorf("missing telemetry callout")
	}
	if !strings.Contains(migrated, "> [!abstract] Architectural Features Implemented") {
		t.Errorf("missing abstract callout")
	}
	if !strings.Contains(migrated, "> [!info] Schema, Data Contracts, & Routing Logic") {
		t.Errorf("missing info callout")
	}
	if !strings.Contains(migrated, "> [!warning] Technical Trade-Offs & Structural Changes") {
		t.Errorf("missing warning callout")
	}

	// Verify no double callouts
	if strings.Count(migrated, "> [!abstract]") != 1 {
		t.Errorf("expected exactly 1 abstract callout, got %d", strings.Count(migrated, "> [!abstract]"))
	}
	if strings.Count(migrated, "> >") > 0 {
		t.Errorf("found nested/broken blockquote markers (> >)")
	}

	// Verify subheadings inside callouts became bold
	if strings.Contains(migrated, "#### Database Schema") {
		t.Errorf("found unescaped #### header inside callout body")
	}
	if !strings.Contains(migrated, "> **Database Schema (Test Fixtures & Dependencies)**") {
		t.Errorf("expected subheading to be converted to bold")
	}

	// 8. Verify footer
	if !strings.Contains(migrated, "*Auto-generated by VaultChron (migrated to v3 callouts)*") {
		t.Errorf("expected migrated footer not found")
	}

	// Test idempotency: re-running on migrated content
	remigrated, err := MigrateContent(migrated, "AcmeWidgets.com", "2026-08-20")
	if err != nil {
		t.Fatalf("Re-running MigrateContent failed: %v", err)
	}
	if remigrated != migrated {
		t.Errorf("MigrateContent is not idempotent!\nDiff:\n%s\nVS\n%s", migrated, remigrated)
	}
}

func TestSlugify(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"Simple", "simple"},
		{"AcmeWidgets.com", "acmewidgets-com"},
		{"--multiple---hyphens--", "multiple-hyphens"},
		{"Special!@#Characters$%", "special-characters"},
		{"123-numbers-456", "123-numbers-456"},
	}

	for _, tt := range tests {
		if got := Slugify(tt.input); got != tt.want {
			t.Errorf("Slugify(%q) = %q, want %q", tt.input, got, tt.want)
		}
		if got := GetSlug(tt.input); got != tt.want {
			t.Errorf("GetSlug(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
